name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0  # versi stable Dart, disarankan hindari versi beta untuk produksi

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  geolocator: ^14.0.2
  google_maps_flutter: ^2.5.2
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/